site-capstone/Backend/config.js
site-capstone/Backend/db.js
site-capstone/Backend/medtracker-schema.sql
site-capstone/Backend/medtracker.sql

- Created database tables
- Added sql file that lets you create and recreate database
- Created pg client for later use in routes and models

Created sql database

---

site-capstone/Backend/app.js
site-capstone/Backend/models/user.js
site-capstone/Backend/routes/auth.js

- Login and register post requests added
- User model created
- Auth routes added to app

Login and Register backend added

---

site-capstone/Frontend/package-lock.json
site-capstone/Frontend/package.json
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.css
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.jsx
site-capstone/Frontend/src/Components/Register/Register.jsx
site-capstone/Frontend/src/components/App/App.jsx

- Added "Create Medication" Page
- Added Error Checking on medication

Added Create Medication Page

---

site-capstone/Frontend/constants.js
site-capstone/Frontend/src/services/apiClient.js

- Added api Client
- Has basic constructor and request
- Added constants file and api url constants
- Added login and register functions for requests

Added apiClient

---

site-capstone/Backend/app.js
site-capstone/Backend/middleware/security.js
site-capstone/Backend/package-lock.json
site-capstone/Backend/package.json
site-capstone/Backend/routes/auth.js
site-capstone/Backend/utils/tokens.js

- Added tokens.js file
- Added security.js file
- Login and Register now work with tokens
- Added /me route that uses tokens to return user info

Added jwt and security middleware

---

site-capstone/Backend/app.js
site-capstone/Backend/medtracker-schema.sql
site-capstone/Backend/middleware/permissions.js
site-capstone/Backend/middleware/security.js
site-capstone/Backend/models/medication.js
site-capstone/Backend/routes/medication.js

- Added post request to create new medication
- Added get request to fetch all user's medication
- Added get request to fetch a medication by Id
- Added permissions middleware

Added Medication routes

---

site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.jsx
site-capstone/Frontend/src/components/App/App.jsx
site-capstone/Frontend/src/services/apiClient.js

- Added createMedication post request to apiClient
- Did the api call in the onSubmit function in the createMedications component

Connected createMedication frontend and backend

---

site-capstone/Frontend/src/components/Landing/Landing.css
site-capstone/Frontend/src/components/Navbar/Navbar.jsx

navbar changes based on login status now fixed

navbar fix 

---

site-capstone/Frontend/src/Components/App/App.jsx
site-capstone/Frontend/src/Components/Dashboard/Dashboard.css
site-capstone/Frontend/src/Components/Dashboard/Dashboard.jsx
site-capstone/Frontend/src/Components/Login/Login.jsx
site-capstone/Frontend/src/Components/Navbar/Navbar.jsx
site-capstone/Frontend/src/Components/Register/Register.jsx

- created dashboard
- updated links to navigate to dashboard 
- deleted redundant css file

created dashboard and updated navbar link and deleted resistor.css

---

site-capstone/Frontend/src/Components/App/App.jsx
site-capstone/Frontend/src/Components/Error Pages/AccessForbidden.jsx
site-capstone/Frontend/src/Components/Error Pages/NotFound.jsx
site-capstone/Frontend/src/Components/LoadingPage/LoadingPage.jsx
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.css
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/Navbar/Navbar.jsx
site-capstone/Frontend/src/Components/ProtectedRoute/ProtectedRoute.jsx
site-capstone/Frontend/src/Components/Register/Register.jsx
site-capstone/Frontend/src/services/apiClient.js

- Edited Access Forbidden, NotFound, and Loading pages
- Edited Medication Details page so that if a user tries to access med details that aren't theirs, they are given an access forbidden error
- Edited Medication Details page so that if a user tries to access med details that don't exist, they are given a not found error
- Added protected routes so that user can't access pages other than the landing, login, and register page unless they are logged. Any attempts to do so will send them to the login page

Forbidden pages

---

site-capstone/Backend/app.js
site-capstone/Backend/config.js
site-capstone/Backend/medtracker-schema.sql
site-capstone/Backend/models/notification.js
site-capstone/Backend/models/user.js
site-capstone/Backend/package-lock.json
site-capstone/Backend/package.json
site-capstone/Backend/routes/notification.js
site-capstone/Frontend/package-lock.json
site-capstone/Frontend/package.json
site-capstone/Frontend/src/Components/App/App.jsx
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.css
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.jsx
site-capstone/Frontend/src/services/apiClient.js

Added notification functionality. User can now set a notification time and frequency and it will create a notification in the db and schedule a schedule job using node-schedule that will send a message to their phone telling them to take their medication. 
Notes to keep in mind for further development:
- Scheduled jobs end after server is shut down
- When we add the delete notification functionality, we must add a unique name to the jobs to be used to cancel them

Added Notifications

---

site-capstone/Backend/medtracker-schema.sql
site-capstone/Backend/models/medication.js
site-capstone/Backend/routes/medication.js
site-capstone/Frontend/src/Components/App/App.jsx
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.jsx
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.jsx
site-capstone/Frontend/src/Components/UpdateMedicationPage/UpdateMedicationPage.jsx
site-capstone/Frontend/src/services/apiClient.js

The edit buttons on the medication card and medication details page both work. They send the user to a edit medication page where the medication info should be prefilled in and where users can update that info. It then updates it in the database. 
The delete button on the medication works and will delete the medication from the database and then refresh the page, with the deleted medication gone.
There edit page is a bit buggy, because sometimes the info does not prepopulate, but the majority of the time it does work. Also, in the future we should add a delete confirmation so that the user does not accidentally delete their medication

Added edit and delete medication

---

site-capstone/Backend/models/notification.js
site-capstone/Frontend/package-lock.json
site-capstone/Frontend/package.json
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.css
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.jsx
site-capstone/Frontend/src/Components/Dashboard/Dashboard.css
site-capstone/Frontend/src/Components/Dashboard/Dashboard.jsx
site-capstone/Frontend/src/Components/Login/Login.css

- Fixed Login page on larger screens
- Added functionality to dashboard as it will now populate with relevant data
- Added styling for mobile on "Create Medications" page
- Edited styling on Dashboard

Populate dashboard

---

site-capstone/Frontend/src/Components/Landing/Landing.css
site-capstone/Frontend/src/Components/Landing/Landing.jsx
site-capstone/Frontend/src/Components/Login/Login.css
site-capstone/Frontend/src/Components/Login/Login.jsx
site-capstone/Frontend/src/Components/Navbar/Navbar.css
site-capstone/Frontend/src/Components/Navbar/Navbar.jsx
site-capstone/Frontend/src/Components/Register/Register.css
site-capstone/Frontend/src/Components/Register/Register.jsx

- Adding more styling to the landing, register, and login page
- Adjusted  login and register buttons sizes in the nav bar to be the same

Landing page edits

---

site-capstone/Backend/models/medication.js
site-capstone/Backend/routes/medication.js
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.css
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/MedicationPage/MedicinePage.jsx
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.css
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.jsx
site-capstone/Frontend/src/services/apiClient.js

Moved refill button to medication details page because of some difficulties getting it to work on the medicine card. It works on the medication details page and automatically updates the current pill count once the user clicks refill in the modal. 
Also after removing the refill button from medicine card, we replaced it with a details button that sends user to medicine details page.
Tidied up code in the medication details, card and page.

Added refill feature

---

site-capstone/Backend/middleware/permissions.js
site-capstone/Backend/models/medication.js
site-capstone/Backend/models/notification.js
site-capstone/Backend/routes/notification.js
site-capstone/Frontend/package-lock.json
site-capstone/Frontend/package.json
site-capstone/Frontend/src/Components/Dashboard/Dashboard.css
site-capstone/Frontend/src/Components/Dashboard/Dashboard.jsx
site-capstone/Frontend/src/Components/Interaction/Interaction.css
site-capstone/Frontend/src/Components/Landing/Landing.css
site-capstone/Frontend/src/Components/Login/Login.css
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.css

- Added next and previous alert times on the details page
- Added frequency timings to the details page for all medications that are scheduled
- Reduced all box shadows sizes
- Updated function for retreiving medication by ID to also pass notifications for that medicine

Med details edits

---

site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx

- Moved handleOnInputChange& handleOnSubmit functions out of IF statement
- No longer crashes on details page

Moved handleOnInputChange& handleOnSubmit functions out of IF statement

---

site-capstone/Backend/models/notification.js
site-capstone/Backend/routes/notification.js
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.jsx
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.css
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.css
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.jsx
site-capstone/Frontend/src/services/apiClient.js

- Medications will delete properly on the front end
- Names for medications will now properly capitalize on all screens 
- Small style edits to buttons

Delete notifications is working on front end. MVP complete.

---

site-capstone/Frontend/src/Components/Dashboard/Dashboard.css
site-capstone/Frontend/src/Components/Landing/Landing.jsx
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.css
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/Register/Register.css

- Updated blurb on the landing page
- style edits that were not addressed yesterday
- Will not display drugbank link if not available

Style adjustments for presentation

---

site-capstone/Backend/routes/notification.js
site-capstone/Frontend/src/Components/Dashboard/Dashboard.jsx
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/UpdateMedicationPage/UpdateMedicationPage.jsx

User can now edit their notification times:
- Change frequency from As Needed to Scheduled and vice versa
- Change notification times
- Change dosage for notification time

Edit notifications

---

site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.jsx

Fixed timezone issue. UTC, EST, MST, & MST supported.

---

site-capstone/Frontend/index.html
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.css
site-capstone/Frontend/src/Components/LoadingPage/LoadingPage.jsx
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.css
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/MedicationPage/MedicinePage.css
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.css
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.jsx
site-capstone/Frontend/src/Components/custom.css
site-capstone/Frontend/src/assets/CustomCss/CustomCss.css

Styling changes

---

site-capstone/Backend/package-lock.json
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.css
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.jsx

- Delete button on press shows a modal asking the user to confirm if they want to delete this specific medication.

Used modal to create confirm delete

---

site-capstone/Frontend/src/Components/Interaction/Interaction.css
site-capstone/Frontend/src/Components/Interaction/Interaction.jsx
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.css
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx

Fix interaction bugs

---

site-capstone/Backend/medtracker-schema.sql
site-capstone/Backend/models/medication.js
site-capstone/Backend/models/notification.js
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.jsx
site-capstone/Frontend/src/Components/Dashboard/Dashboard.jsx
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/MedicationPage/MedicinePage.jsx
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.jsx
site-capstone/Frontend/src/Components/custom.css
site-capstone/Frontend/src/assets/CustomCss/CustomCss.css

- Fixed timezone's on all pages
- Timezones times updates on medicine details pages
- You get notified at your local time

Fix details timings

---

site-capstone/Frontend/src/Components/UpdateMedicationPage/UpdateMedicationPage.jsx

Added auto complete functionality to update medications page.
Made sure error checking still works with it

Added auto complete to update medications page

---

site-capstone/Frontend/src/Components/Interaction/Interaction.css
site-capstone/Frontend/src/Components/Interaction/Interaction.jsx

Interaction updates

---

site-capstone/Backend/package.json
site-capstone/Frontend/src/Components/Autocomplete/useAutocomplete.js
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.css
site-capstone/Frontend/src/Components/CreateMedicationPage/CreateMedicationPage.jsx
site-capstone/Frontend/src/Components/Interaction/Interaction.jsx
site-capstone/Frontend/src/Components/Landing/Landing.css
site-capstone/Frontend/src/Components/Landing/Landing.jsx
site-capstone/Frontend/src/Components/Login/Login.jsx
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.css
site-capstone/Frontend/src/Components/MedicationDetails/MedicationDetails.jsx
site-capstone/Frontend/src/Components/MedicationPage/MedicinePage.jsx
site-capstone/Frontend/src/Components/MedicineCard/MedicineCard.jsx
site-capstone/Frontend/src/Components/Navbar/Navbar.css
site-capstone/Frontend/src/Components/Navbar/Navbar.jsx
site-capstone/Frontend/src/Components/Register/Register.jsx
site-capstone/Frontend/src/Components/UpdateMedicationPage/UpdateMedicationPage.css
site-capstone/Frontend/src/Components/UpdateMedicationPage/UpdateMedicationPage.jsx

- changed css on buttons
- lowered amount of autofills shown

Btn css changes
